image: Visual Studio 2017 Preview
configuration: Release

environment:
  SignClientSecret:
    secure: S26+NphAhj/vo5ZdHd/N/4toty3ztdNGmuNdvAB57W1oIVQEHVKqAVuhTD8B9ATy

init:
  - git config --global core.autocrlf input

skip_branch_with_pr: true

install:
  - cmd: appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/v4.1.0/NuGet.exe
  - cmd: nuget install SignClient -Version 0.7.0 -SolutionDir %APPVEYOR_BUILD_FOLDER% -Verbosity quiet -ExcludeVersion

build_script:
  - cmd: dotnet pack -c Release -o %APPVEYOR_BUILD_FOLDER%
  - cmd: dotnet test -c Release RSAKeyVaultProvider.Tests\RSAKeyVaultProvider.Tests.csproj

after_build:
  - ps: '.\SignClient\Sign-Package.ps1'
  
artifacts:
  - path: '*.nupkg'
  
test: off
  