image: Visual Studio 2017
configuration: Release

environment:
  SignClientSecret:
    secure: EvUuRb2cdsB5h7dJ49CkDDsZHHbwomGvMbcVcRsCSIp58IxVHFzAZrJSE+qpihtU
  SignClientUser:
    secure: 9nw9iBguE89m36udK51REeCIHSi5lAXmFIfS5LuAXio=

init:
  - git config --global core.autocrlf input

skip_branch_with_pr: true

skip_commits:
  files:
    - '**/*.md'

install:
  - cmd: nuget install SignClient -Version 0.9.0 -SolutionDir %APPVEYOR_BUILD_FOLDER% -Verbosity quiet -ExcludeVersion

build_script:
  - cmd: dotnet build -c Release /p:PackageOutputPath=%APPVEYOR_BUILD_FOLDER%
  - cmd: dotnet test -c Release RSAKeyVaultProvider.Tests\RSAKeyVaultProvider.Tests.csproj

after_build:
  - ps: '.\scripts\Sign-Package.ps1'
  
artifacts:
  - path: '*.nupkg'
  
test: off

deploy:
  provider: NuGet
  server: https://www.myget.org/F/rsakeyvaultprovider/api/v2/package
  symbol_server: https://www.myget.org/F/rsakeyvaultprovider/symbols/api/v2/package
  api_key:
    secure: bmqlJK8a5HYiUXOT99HXT1j7JiM5+fpR4kHhxIC30oaaEXbv94f0fKdiKlU1QC/l
  artifact: /.*\.nupkg/