image: Visual Studio 2017
configuration: Release

environment:
  SignClientSecret:
    secure: S26+NphAhj/vo5ZdHd/N/4toty3ztdNGmuNdvAB57W1oIVQEHVKqAVuhTD8B9ATy

init:
  - git config --global core.autocrlf input

skip_branch_with_pr: true

skip_commits:
  files:
    - '**/*.md'

install:
  - cmd: appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/v4.1.0/NuGet.exe
  - cmd: nuget install SignClient -Version 0.7.0 -SolutionDir %APPVEYOR_BUILD_FOLDER% -Verbosity quiet -ExcludeVersion

build_script:
  - cmd: dotnet build -c Release /p:PackageOutputPath=%APPVEYOR_BUILD_FOLDER%
  - cmd: dotnet test -c Release RSAKeyVaultProvider.Tests\RSAKeyVaultProvider.Tests.csproj

after_build:
  - ps: '.\scripts\Sign-Package.ps1'
  
artifacts:
  - path: '*.nupkg'
  
test: off

deploy:
  provider: NuGet
  server: https://www.myget.org/F/rsakeyvaultprovider/api/v2/package
  symbol_server: https://www.myget.org/F/rsakeyvaultprovider/symbols/api/v2/package
  api_key:
    secure: bmqlJK8a5HYiUXOT99HXT1j7JiM5+fpR4kHhxIC30oaaEXbv94f0fKdiKlU1QC/l
  artifact: /.*\.nupkg/